### PR TITLE
use consistent flexbox grid for Showcase, Developers, and Team (and add Team photos and nothing else to see here)

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by cvan** [comment]
screenshot 2016-02-19 14 00 13
screenshot 2016-02-19 14 00 02

**Comment by cvan** [comment]
tested in all browsers on desktop, iOS - looks good

**Comment by cvan** [comment]
r+

**Comment by caseyyee** [comment]
nice thanks

**Pull request merged**
