### PR TITLE
improve text loading due to webfonts (fixes #61)

### LINKED ISSUE #61: Web font takes too long to load (especially on mobile)

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by caseyyee** [comment]
Neat solution.   But doesn't the text just not render until the font is available?

Also, given fat fonts like this.  There may be a better font format that is a little quicker to download?   They are each in the 100's of kb in size.   Might compress well over the wire though.

**Comment by cvan** [comment]
Neat solution. But doesn't the text just not render until the font is available?

**Comment by cvan** [comment]
> Neat solution. But doesn't the text just not render until the font is available?

That's what this prevents. If `body` contains a `font-family` that isn't downloaded yet, the text will be blank until the font is available - and this behaviour is the same in all browsers, unfortunately.

The Chrome team is working a spec to change this behaviour.

> Also, given fat fonts like this. There may be a better font format that is a little quicker to download? 

We provide woff2 fonts, which is currently the best font format, but that's of course supported by only Firefox and Chrome (and Opera). That's probably why you've never noticed any issues on desktop or from Chrome for Android.

Safari on desktop and mobile - that's another story. I've waited ~10s for text to show up on Safari mobile … even on Mozilla WiFi. It looks pretty bad.

**Comment by caseyyee** [comment]
Sorry, need to rebase.

**Comment by cvan** [comment]
merging

**Pull request merged**
